export const data: string[]= ["Sanal ortamda zamanın nasıl geçtiğini fark etmem.", 
    "Kısa bir süre için girdiğim internette daha uzun zaman harcarım.",
    "Bildirim gelmediğinde bile cep telefonumu belli aralıklarla kontrol ederim.",
    "Telefon ve tablet gibi mobil cihazlarımı evde unuttuğumda kendimde eksiklik duygusu yaşarım.",
    "Ekran karşısında geçirdiğim zaman yüzünden bazı sorumluluklarımı ihmal etmiş olabilirim.",
    "Çevrimiçi olamadığım veya olmadığımda bir şeyleri kaçırdığım hissiyle rahatsız olurum.",
    "Elektronik cihazlarımla daha mutluyum.",
    "Günlük yaşantımız ekranlar tarafından istila edilmektedir.",
    "Uykuya dalmadan önce elektronik cihazlarımı son bir kez kontrol ederim.",
    "Ekranlar karşısında aşırı zaman geçirdiğim gerekçesiyle yakın çevrem tarafından uyarıldım.",
    "Beslenme ve diğer ihtiyaçlarımı karşılarken akıllı telefonum yanımda olur.",
    "Sanal ortama girdiğimde veya elektronik cihazları kullanmaya başladığımda gerçek kaygı ve problemlerimi unuturum.",
    "Elektronik cihazlardan uzun süre uzak kalamam.",
    "Elektronik cihazlardan biriyle meşgulken başka bir cihazı da kontrol ederim.",
    "Eve geldiğimde hemen elektronik cihazlara yönelirim.",
    "Geceleri, elektronik cihazlarla meşgulsem daha geç uyurum.",
    "Gece telefonumu açık tutarım.",
    "Elektronik cihazları kullanışımın herhangi bir nedenle kısıtlanması veya engellenmem benim için ciddi bir sorundur.",
    "Zihnim çoğunlukla elektronik cihazlarla meşgul olur.",
    "Hastalık durumlarında hemen doktora gitmek veya bir uzmana danışmak yerine önce internet araştırması yapmayı tercih ederim.",
    "Merak ettiğim her şey için internete bakarım.",
    "Mobil cihazlarımın bataryasının azalması beni endişelendirir.",
    "Her gün sosyal medyayı kullanırım.",
    "Uyanır uyanmaz akıllı telefonumu kontrol ederim.",
    "Günümüzde çevrimiçi olmak bir zorunluluktur.",
    "Cep telefonum uyurken bile başucumdadır.",
    "Yeni bir elektronik cihazı kullanmam gerektiğinde strese girerim.",
    "Gerçek yaşamda karşılayamadığım ihtiyaçları, sanal ortamda karşılamayı tercih ederim.",
    "Daha fazla mutlu olmak için teknolojiyle daha çok vakit geçiririm.",
    "Teknolojik araçların olmadığı bir dünyayı hayal edemiyorum.",
    "Yeni çıkan elektronik cihazları takip eder ve satın alırım.",
    "Herhangi bir nedenle elektronik cihazlardan uzak kalmak veya kullanım kısıtlaması beni strese sokar."
];